language: node_js
node_js: 5
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y erlang
  - epmd -daemon
script:
  - npm run lint
  - npm run coverage
  - ls -lah coverage/
  - npm run coveralls
cache:
  directories:
    - node_modules
