language: node_js
node_js: 5.1.x
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y erlang
  - epmd -daemon
script:
  - npm run lint
  - npm run coverage
  - ls -lah .
  - npm run coveralls
